# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build154-211:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -f module/pom.xml install && mvn exec:exec -Dexec.executable="java" -Dxmlcalabash.version=1.5.4-100 -Dxml.resolver=2.1.1
        
  build154-512:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -f module/pom.xml install && mvn exec:exec -Dexec.executable="java" -Dxmlcalabash.version=1.5.4-100 -Dxml.resolver=5.1.2
        
  build153-211:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -f module/pom.xml install && mvn exec:exec -Dexec.executable="java" -Dxmlcalabash.version=1.5.3-100 -Dxml.resolver=2.1.1
        
  build153-460:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -f module/pom.xml install && mvn exec:exec -Dexec.executable="java" -Dxmlcalabash.version=1.5.3-100 -Dxml.resolver=4.6.0